version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user_x
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://user_x:password@db:5432/social_network
      - DJANGO_SECRET_KEY=django-insecure-dx*$yofdhss0py!2m^3wbf3dun-l*2!#t7b*o$c2gt1@z6n^(k)
    depends_on:
      - db
      - redis  # Add redis dependency for web service

  redis:
    image: "redis:alpine"  # Redis service definition
    ports:
      - "6380:6379"

volumes:
  postgres_data:
